### PR TITLE
Initial draft of the app

### PR DESCRIPTION
**Pull request by shahreyar-abeer**
Hi guys, this is an initial draft of the app.
The first two tabs are the working ones at the moment.
Please review it and let me know what you think of it.
It took ~10 hours to build this.

### CODE REVIEW

**Comment by RobertASmithBresMed** [comment]
Awesome thanks.

I'll add a round of initial comments here and then let Paul and Wael add in their own time:

- There are some dependencies which should presumably be included in the package dependencies.
- When the 'run_app' function is run the academic paper is downloaded as a pdf. I assume this is not intentional?
- The academic paper PDF iframe length could be longer (down to the base of the page).
- Could you add Wael to the list of people on the bottom right (https://www.linkedin.com/in/wael-mohammed/)
- There is a lot here, so thanks, I will build in Issue 5 (the report) at a later date.
- I have not deployed an app created using `golum` on shinyapps.io before, do you have any experience with this?

**Comment by shahreyar-abeer** [comment]
To address your points

*  Although it is built as a package, this app is not meant to function like that unless absolutely necessary.
This is due to the fact that setting it up as a package will require some extra work which is not in out interest at the moment.  
So I'd say it's best to treat it as an 'ordinary' shiny app instead of an R package as of now.
*  I'll add a file that will let the user run the app by clicking a 'Run App' icon on top of the file, just like a standard shiny app. And it will also let us deploy on shinyapps.io like other shiny apps.  
* I'll take of the rest of the points Inn Shaa Allah.

**Comment by RobertASmithBresMed** [comment]
Great, thankyou - let me know when done and I'll merge changes & deploy. I tried to deploy earlier and got an error, would be great if you could check that deployment works for you on shinyapps.io.

**Comment by shahreyar-abeer** [comment]
App deployed to shinyapps.io
https://shahreyar-abeer.shinyapps.io/livinghtademo/

**Comment by RobertASmithBresMed** [comment]
Awesome, I can now deploy the same app on shinyapps. 

However both my version (https://rasmithbresmed.shinyapps.io/app_golem/) and your version breaks when attempting to run the model : 
image

Any ideas on why this may be?

**Comment by shahreyar-abeer** [comment]
image

Okay, problem fixed.
Please give it a try now (pulling the latest changes).

**Comment by RobertASmith** [comment]
Awesome, thanks that works.

**Pull request merged**
